```plantuml
@startuml
title File Logging Model

class FileHandler {
    +FilePath : string
    --
    +FileHandler(filePath : string)
    +WriteToFile(content : string) : void
    +ReadFromFile() : string
}

class LogFile {
    +LogFile(filePath : string)
    +AppendLog(logMessage : string) : void
}


LogFile -u-|> FileHandler : <<extends>>

hide empty members
@enduml
```
